trigger:
- none

pool:
  vmImage: ubuntu-latest

steps:
- task: MavenAuthenticate@0
  inputs:
    artifactsFeeds: 'mevijays, public'
  displayName: Auth to feeds mevijays
- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean deploy'
    options: '-gs .mvn/settings.xml'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    codeCoverageToolOption: 'JaCoCo'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
